# Sales Data Analysis using SQL, SQLite & Python

## Objective: **bold text**
To analyze sales data and generate insights on customer behavior, regional performance, and product categories.

## Tools Used:
- Python (Pandas)
- SQLite
- SQL
- Looker Studio (Dashboard)

## Workflow:
CSV → SQLite → SQL Queries → Insights → Dashboard

## Key Insights:

- West region has highest number of orders.
- Technology category generates highest profit.
- Standard Class is the most used shipping mode.
- Certain cities contribute significantly to overall sales.

In [1]:
import pandas as pd

df = pd.read_csv("csv_data.csv")

df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [2]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [3]:
import sqlite3

conn = sqlite3.connect("orders.db")

df.to_sql("orders", conn, if_exists="replace", index=False)

print("Database created successfully!")

Database created successfully!

In [4]:
query = "SELECT COUNT(*) as total_orders FROM orders"
pd.read_sql_query(query, conn)

   total_orders
0          9994

CORE PROJECT IDEA START

1. Orders by Region

In [5]:
query = """
SELECT Region, COUNT(*) as total_orders
FROM orders
GROUP BY Region
ORDER BY total_orders DESC
"""
pd.read_sql_query(query, conn)

    Region  total_orders
0     West          3203
1     East          2848
2  Central          2323
3    South          1620

2. Orders by Category

In [6]:
query = """
SELECT Category, COUNT(*) as total
FROM orders
GROUP BY Category
"""
pd.read_sql_query(query, conn)

          Category  total
0        Furniture   2121
1  Office Supplies   6026
2       Technology   1847

3. Orders by Segment

In [ ]:
query = """
SELECT Segment, COUNT(*) as total
FROM orders
GROUP BY Segment
"""
pd.read_sql_query(query, conn)

4. Ship Mode Distribution

In [7]:
query = """
SELECT "Ship Mode", COUNT(*) as total
FROM orders
GROUP BY "Ship Mode"
"""
pd.read_sql_query(query, conn)

        Ship Mode  total
0     First Class   1538
1        Same Day    543
2    Second Class   1945
3  Standard Class   5968

5. Top Cities

In [ ]:
query = """
SELECT City, COUNT(*) as total_orders
FROM orders
GROUP BY City
ORDER BY total_orders DESC
LIMIT 5
"""
pd.read_sql_query(query, conn)

6. SALES ANALYSIS

In [ ]:
query = """
SELECT Region, SUM(Sales) as total_sales
FROM orders
GROUP BY Region
ORDER BY total_sales DESC
"""
pd.read_sql_query(query, conn)

PROFIT ANALYSIS

In [ ]:
query = """
SELECT Category, SUM(Profit) as total_profit
FROM orders
GROUP BY Category
ORDER BY total_profit DESC
"""
pd.read_sql_query(query, conn)

In [8]:
from google.colab import files
files.download("orders.db")